/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Seating Planner API
 * REST API for the seating planner application
 * OpenAPI spec version: 1.0.0
 */
/**
 * Response for /api/hello endpoint
 */
export interface HelloResponse {
  /** Hello message */
  message?: string;
  /** Server time in milliseconds */
  timestamp?: number;
}

/**
 * Returns a greeting message with timestamp
 * @summary Get hello
 */
export type sayHelloResponse200 = {
  data: HelloResponse
  status: 200
}
    
export type sayHelloResponseSuccess = (sayHelloResponse200) & {
  headers: Headers;
};
;

export type sayHelloResponse = (sayHelloResponseSuccess)

export const getSayHelloUrl = () => {


  

  return `/hello`
}

export const sayHello = async ( options?: RequestInit): Promise<sayHelloResponse> => {
  
  const res = await fetch(getSayHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sayHelloResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sayHelloResponse
}
